"""empty message

Revision ID: c31fe4f8bda5
Revises: 9c1b39b839b2
Create Date: 2020-10-31 20:05:13.004625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c31fe4f8bda5'
down_revision = '9c1b39b839b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plot_interval',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('starting_time', sa.DateTime(), nullable=True),
    sa.Column('ending_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plot_interval')
    # ### end Alembic commands ###
